[package]
name = "drummond"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
ctrlc = "3.4.7"
midir = "0.10.2"
midly = "0.5.3"
rustyline = "17.0.1"
serialport5 = "5.0.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
